add:account_models_first commit
wecode-bootcamp-korea/12-jidealogitech-backend pull request #2
Opened 2020-09-17 10:03 UTC by gorusair

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 버튼 활성화 기능 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- id '@' 포함, pw 5 글자 이상 입력 시 버튼 활성화(예시)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-09-18 06:42 UTC, lordmyshepherd requested changes

2020-09-18 06:42 UTC, lordmyshepherd commented on account/models.py
> +    password       =   models.CharField(max_length=20)
동현님! models.py를 잘 작성하고 계시군요!!
여기서, password는 암호화해서 저장하게되는데, 이 경우 max_length=20은 짧아서 Database에 저장할 때, 에러가 발생할 것 같습니다! 수정해주세요~ 👍

2020-09-18 06:42 UTC, lordmyshepherd commented on account/models.py
> +    language       =   models.CharField(max_length=50, null=True)
null=True 속성을 주신 이유가 있나요??

2020-09-18 06:42 UTC, lordmyshepherd commented on account/models.py
> +    #product       =  models.ForeignKey(Account, on_delete=models.CASCADE,null=True)
개발단계에서는 사용하셔도 되지만, 중요한 내용을 전달하는 목적이 아니라면, `주석`은 지워주세요~

2020-09-18 06:42 UTC, lordmyshepherd commented on order/models.py
> +#from products.models import Product
주석은 지워주세요~

2020-09-18 06:42 UTC, lordmyshepherd commented on order/models.py
> +    product_title  = models.ManyToManyField("self")
ManyToManyField를 사용할 경우, 중간 테이블을 만들어서 사용해주세요!
아래 링크를 참고해서 만들어보세요!
https://docs.djangoproject.com/en/3.1/ref/models/fields/#django.db.models.ManyToManyField
![스크린샷 2020-09-18 오후 3 40 31](https://user-images.githubusercontent.com/53214510/93564820-4afa1b80-f9c5-11ea-8f93-0cecfd48f8e0.png)

2020-09-18 06:42 UTC, lordmyshepherd commented on order/models.py
> +    #account        = models.ForeignKey(Account, on_delete=models.CASCADE)
마찬가지로 주석은 지워주세요.

2020-09-18 06:42 UTC, lordmyshepherd commented on order/models.py
> +    #product        = models.ForeignKey(Product, on_delete=models.CASCADE)
마찬가지 입니다.

2020-09-19 03:31 UTC, soheon-lee commented on account/models.py
> +    birthday       =   models.IntegerField(default=0,  null=True)
```suggestion
    birthday       =   models.DateField(null=True)
```
생년월일은 날짜 이므로 datefield로 관리하시는 것이 좋습니다 :)

2020-09-19 03:33 UTC, soheon-lee commented on account/models.py
> +    phone          =   models.IntegerField(default=0)
```suggestion
    phone          =   models.CharField(default=0)
```
핸드폰 번호는 정수가 아닙니다. 숫자처럼 보이긴 하지만 사실 '정수'로서의 역할을 하지 않죠. 정수라면 번호 제일 앞의 `0`이 무시될 수도 있습니다 문자열로 관리해주세요 :)

2020-09-19 03:38 UTC, merged